// JavaScript Document
$(document).ready(function() {
	$('.all_opt').animate({opacity:1},1000);
	$('#all_btn').click(function(){
		$('.all_opt').animate({opacity:1},1000);
		$('.web_opt').animate({opacity:0},1000);
		$('.mob_opt').animate({opacity:0},1000);
		$('.pg_opt').animate({opacity:0},1000);
		$('.cold_opt').animate({opacity:0},1000);
		$('.fl_opt').animate({opacity:0},1000);
	});
	$('#web_btn').click(function(){
		$('.all_opt').animate({opacity:0},1000);
		$('.web_opt').animate({opacity:1},1000);
		$('.mob_opt').animate({opacity:0},1000);
		$('.pg_opt').animate({opacity:0},1000);
		$('.cold_opt').animate({opacity:0},1000);
		$('.fl_opt').animate({opacity:0},1000);
	});
	$('#mob_btn').click(function(){
		$('.all_opt').animate({opacity:0},1000);
		$('.web_opt').animate({opacity:0},1000);
		$('.mob_opt').animate({opacity:1},1000);
		$('.pg_opt').animate({opacity:0},1000);
		$('.cold_opt').animate({opacity:0},1000);
		$('.fl_opt').animate({opacity:0},1000);
	});
	$('#pg_btn').click(function(){
		$('.all_opt').animate({opacity:0},1000);
		$('.web_opt').animate({opacity:0},1000);
		$('.mob_opt').animate({opacity:0},1000);
		$('.pg_opt').animate({opacity:1},1000);
		$('.cold_opt').animate({opacity:0},1000);
		$('.fl_opt').animate({opacity:0},1000);
	});
	$('#cold_btn').click(function(){
		$('.all_opt').animate({opacity:0},1000);
		$('.web_opt').animate({opacity:0},1000);
		$('.mob_opt').animate({opacity:0},1000);
		$('.pg_opt').animate({opacity:0},1000);
		$('.cold_opt').animate({opacity:1},1000);
		$('.fl_opt').animate({opacity:0},1000);
	});
	$('#fl_btn').click(function(){
		$('.all_opt').animate({opacity:0},1000);
		$('.web_opt').animate({opacity:0},1000);
		$('.mob_opt').animate({opacity:0},1000);
		$('.pg_opt').animate({opacity:0},1000);
		$('.cold_opt').animate({opacity:0},1000);
		$('.fl_opt').animate({opacity:1},1000);
	});
});
